name: marsin_site
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  image_picker_web: ^3.0.0+1
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.11.0
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - assets/images/
    - assets/icons/


  fonts:
    - family: IBMPlexSerif
      fonts:
        - asset: fonts/IBMPlexSerif-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/IBMPlexSerif-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexSerif-Regular.ttf